# Generated by Django 3.0.7 on 2020-06-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('symbol_type', models.CharField(choices=[('body_of_water', 'body_of_water'), ('bridge', 'bridge'), ('building', 'building'), ('city', 'city'), ('college', 'college'), ('commemorative_license_plate', 'commemorative_license_plate'), ('county', 'county'), ('flag', 'flag'), ('highway_or_roadway', 'highway_or_roadway'), ('holiday_or_observances', 'holiday_or_observances'), ('marker', 'marker'), ('military_Base', 'military_Base'), ('monument', 'monument'), ('other', 'other'), ('park', 'park'), ('plaque', 'plaque'), ('scholarship', 'scholarship'), ('school', 'school'), ('seal', 'seal'), ('song', 'song')], max_length=30)),
            ],
        ),
    ]
