# Generated by Django 3.0.7 on 2020-06-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Honoree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('symbol_type', models.CharField(choices=[('body_of_water', 'body_of_water'), ('bridge', 'bridge'), ('building', 'building'), ('city', 'city'), ('college', 'college'), ('commemorative_license_plate', 'commemorative_license_plate'), ('county', 'county'), ('flag', 'flag'), ('highway_or_roadway', 'highway_or_roadway'), ('holiday_or_observances', 'holiday_or_observances'), ('marker', 'marker'), ('military_Base', 'military_Base'), ('monument', 'monument'), ('other', 'other'), ('park', 'park'), ('plaque', 'plaque'), ('scholarship', 'scholarship'), ('school', 'school'), ('seal', 'seal'), ('song', 'song')], max_length=30)),
                ('petition_link', models.CharField(blank=True, default='', max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('contacts', models.ManyToManyField(to='symbols.Contact')),
                ('honoree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='symbols.Honoree')),
            ],
        ),
    ]
