# Generated by Django 3.0.7 on 2020-06-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='symbol',
            name='petition_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='symbol',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='symbol',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='symbol',
            name='zip_code',
            field=models.CharField(default=11111, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='symbol',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='county',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
