# Generated by Django 3.0.7 on 2020-06-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('honorees', '0001_initial'),
        ('symbols', '0002_auto_20200613_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='contacts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='contacts.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='honorees',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='honorees.Honoree'),
            preserve_default=False,
        ),
    ]
