# Generated by Django 3.0.7 on 2020-06-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('symbols', '0003_auto_20200613_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='honorees',
            new_name='honoree',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='contacts',
        ),
        migrations.AddField(
            model_name='symbol',
            name='contacts',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
