# Generated by Django 3.0.7 on 2020-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('symbols', '0004_auto_20200613_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='contacts',
            field=models.ManyToManyField(null=True, to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='petition_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
