# Generated by Django 3.0.7 on 2020-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('symbols', '0005_auto_20200613_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='contacts',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
