# Generated by Django 3.0.7 on 2020-06-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honorees', '0001_initial'),
        ('symbols', '0007_auto_20200613_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='honoree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='honorees.Honoree'),
        ),
    ]
