# Generated by Django 3.0.7 on 2020-06-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0010_auto_20200613_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='contacts',
            field=models.ManyToManyField(to='symbols.Contact'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='honoree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='symbols.Honoree'),
        ),
    ]
